### ISSUE TITLE
Seekbar position reset to 0 when relaunching

### ISSUE THREAD

**Issue by naghub** [googlesamples/android-MediaBrowserService#8]
Steps:
1. Open the player
2. Play some audio
3. Seek to middle for better understanding
4. Press 'Back' which minimises app.
5. Start over, see seekbar position reset to 0, sometimes no progress after this.

**Comment by naghub** [comment]
@yigit, @JoseAlcerreca, @florina-muntenescu, @ChrisCraik, @jonathan-caryl, @ianhanniballake

Please check

**Comment by naghub** [comment]
Calling below method from `MediaBrowserListener.onPlaybackStateChanged` fixed the issue.

`private void updateProgressWithDelay() {
        if (mLastPlaybackState != null) {
            new Handler().postDelayed(() -> {
                long lastPosition = mLastPlaybackState.getPosition();
                long timeDelta = SystemClock.elapsedRealtime() -
                        mLastPlaybackState.getLastPositionUpdateTime();
                long currentPosition = lastPosition + (int) (timeDelta
                        * mLastPlaybackState.getPlaybackSpeed());
                LogHelper.e(TAG, "mSeekBarAudio.setProgress() " + currentPosition);
                //mSeekBarAudio.setProgress(0);
                mSeekBarAudio.setProgress((int) currentPosition);
            }, 200);
        }
    }`

Please let me know if there is a better way to do this.

**Comment by josydeleon** [comment]
@naghub seekBar set to the last position but it does not continue with the animation of progress.

**Comment by cartland** [comment]
Hello, I suggest looking at the "UAMP" sample: https://github.com/googlesamples/android-UniversalMusicPlayer.

The UAMP sample contains a MediaBrowserService implementation that works with more Android features.
https://android-developers.googleblog.com/2018/06/a-new-universal-music-player.html
https://medium.com/androiddevelopers/making-the-uamp-sample-an-instant-app-30c3f0a050af

If this issue is still reproducible in the UAMP sample, please open an issue there. Thank you!
